### ISSUE TITLE
Publish NuGet version with FluentNHibernate 2.0-alpha and NHibernate 4.0

### ISSUE THREAD

**Issue by tlycken** [haf/Castle.Facilities.NHibernate#22]
In the process of updating our project (NCVIB :smirk:) to NHibernate 4.0, we needed to update this as well, since it depends on the older versions. After some struggling with rake building (see #21) I managed to build this project in Visual Studio, and the only thing I had to do to make the main project build with the new NHibernate libraries was to go to the package manager console and say

```
PM> Update-Package NHibernate
PM> Update-Package FluentNHibernate -Pre
```

Tests didn't compile after that, because the classes `C1` *et al* don't implement all members of `INHibernateInstaller` (don't know how that worked before...) but other than that everything seems fine. If I just add the missing methods and leave them empty, all tests pass. And if I replace the dlls in our project by the one produced by this VS build, our project also compiles again (except for similar missing methods on `INHibernateInstaller´ implementations).

Would you mind doing the corresponding NuGet updates and publish a version that supports the updated NHibernate libraries? Also, is there any need to add non-empty implementations for the new methods if we don't want any change in behavior?

**Comment by Oberheim** [comment]
I am in the process of upgrading a solution to use FluentNHibernate 2.0.1.0 and NHibernate 4.0 as well and am stuck at the same compile error as tlycken and I am guessing that you guys made no progress past that.

**Comment by haf** [comment]
The reason is the build files. Just create a new C# project in visual studio, replacing the old project files, and add the .cs files to the new C# project. Easy as pie. PR. Merge, release.
