### ISSUE TITLE
object null reffrence to use nhibernate cache

### ISSUE THREAD

**Issue by EngRajabi** [haf/Castle.Facilities.NHibernate#30]
im use nhibernate syscache2 , config UseQueryCache = true .
exception object null reffrence.
nhibernate 5.1
nhibernate syscache 5.3

**Comment by haf** [comment]
Not enough information

**Comment by EngRajabi** [comment]
if use install package nhibernate syscache2 , and set nhibernate config . nhibernate use cache , 
```
Container.AddFacility<NHibernateFacility>(x =>
{
          x.FlushMode = FlushMode.Commit;
          x.DefaultLifeStyle = defaultLifeStyle;      
});
```
exception object null reffrence.

**Comment by haf** [comment]
It's probably because this nuget hasn't been released in about 5 years and is by all means not maintained. If you're interested in using it, feel free to fork it.
